/*
const STARS = {
    stars2:require('../assets/images/Stars2.png'),
    stars3:require('../assets/images/Stars3.png'),
    stars4:require('../assets/images/Stars4.png'),
    stars5:require('../assets/images/Stars5.png')
}

export const PRODUCTS =[
        {
            image:require('../assets/images/TamaDrumset.jpg'),
            altImage:"Tama Drumset",
            nameNormal:"Tama Drumset Rhythm Mate RM50YH6 CPM",
            name:"Tama Drumset Rhythm\n Mate RM50YH6 CPM",
            prize:"735",
            stars:STARS.stars3,
            altStars:"3 stars",
            id:"1",
        },
        {
            image:require('../assets/images/Doumbek.png'),
            altImage:"Meinl Doumbek",
            nameNormal:"Meinl Artisan Doumbek Queen",
            name:"Meinl Artisan Doumbek\nQueen",
            prize:"377",
            stars:STARS.stars3,
            altStars:"3 stars",
            id:"2",
        },
        {
            image:require('../assets/images/handpan.jpg'),
            altImage:"Meinl Handpan",
            nameNormal:"Meinl Sonic Energy HPSTL90 Handpan Vintage Gold D Kurd",
            name:"Meinl Sonic Energy\nHPSTL90 Handpan Vintag...",
            prize:"1,789",
            stars:STARS.stars5,
            altStars:"5 stars",
            id:"3",
        },
        {
            image:require('../assets/images/Marimba.jpg'),
            altImage:"Yamaha Marimba",
            nameNormal:"Yamaha Marimba YM6100",
            name:"Yamaha Marimba YM6100\n\n",
            prize:"23,541",
            stars:STARS.stars5,
            altStars:"5 stars",
            id:"4",
        },
        {
            image:require('../assets/images/WoodBlock.jpg'),
            altImage:"NP Wood Block",
            nameNormal:"NP Wood Block Special 05035",
            name:"NP Wood Block Special\n05035",
            prize:"23.40",
            stars:STARS.stars3,
            altStars:"3 stars",
            id:"5",
        },
        {
            image:require('../assets/images/Bongos.jpg'),
            altImage:"LP CP Bongos",
            nameNormal:"LP CP Traditional Bongos, Natural",
            name:"LP CP Traditional Bongos,\nNatural",
            prize:"53.90",
            stars:STARS.stars2,
            altStars:"2 stars",
            id:"6",
        },
        {
            image:require('../assets/images/bongos2.jpg'),
            altImage:"Bongo Martín Cohen",
            nameNormal:"LP LP200F-MC Bongo Martin Cohen L.E.",
            name:"LP LP200F-MC Bongo\nMartin Cohen L.E.",
            prize:"349",
            stars:STARS.stars5,
            altStars:"5 stars",
            id:"7",
        },
        {
            image:require('../assets/images/bongos3.jpg'),
            altImage:"Toca Bongo Synergy",
            nameNormal:"Toca Bongo Synergy Wine Burst",
            name:"Toca Bongo Synergy Wine\nBurst",
            prize:"191",
            stars:STARS.stars3,
            altStars:"3 stars",
            id:"8",
        },
        {
            image:require('../assets/images/bongos4.jpg'),
            altImage:"LP Bongo Matador Cuba",
            nameNormal:"LP Bongo Matador Cuba M201QBA",
            name:"LP Bongo Matador Cuba\nM201QBA",
            prize:"239",
            stars:STARS.stars4,
            altStars:"4 stars",
            id:"9",
        },
        {
            image:require('../assets/images/bongos5.jpg'),
            altImage:"LP Bongo Mini",
            nameNormal:"LP LP817950 - Bongo Mini, Natural",
            name:"LP LP817950 - Bongo Mini,\nNatural",
            prize:"78.17",
            stars:STARS.stars3,
            altStars:"3 stars",
            id:"10",
        },
        {
            image:require('../assets/images/bongos6.jpg'),
            altImage:"LP Bongo Matador",
            nameNormal:"LP Bongo Matador M201-AW",
            name:"LP Bongo Matador\nM201-AW",
            prize:"249",
            stars:STARS.stars4,
            altStars:"4 stars",
            id:"11",
        },
        {
            image:require('../assets/images/bongos7.jpg'),
            altImage:"LP Bongo Anniversary",
            nameNormal:"LP Bongo 60th Anniversary B-Stock",
            name:"LP Bongo 60th Anniversary\nB-Stock",
            prize:"354",
            stars:STARS.stars5,
            altStars:"5 stars",
            id:"12",
        },
        {
            image:require('../assets/images/bongos8.jpg'),
            altImage:"Meinl Spectrum Bongos",
            nameNormal:"Meinl S400PBK Spectrum Series Bongos 7\" and 8 1/2\" Phantom Black",
            name:"Meinl S400PBK Spectrum\nSeries Bongos 7 and 8...",
            prize:"449.20",
            stars:STARS.stars5,
            altStars:"5 stars",
            id:"13",
        },
        {
            image:require('../assets/images/drumset2.jpg'),
            altImage:"Tama Lars Drumset",
            nameNormal:"Tama Imperialstar Lars Ulrich L.E.",
            name:"Tama Imperialstar Lars\nUlrich L.E.",
            prize:"1.490",
            stars:STARS.stars5,
            altStars:"5 stars",
            id:"14",
        },
        {
            image:require('../assets/images/drumset3.jpg'),
            altImage:"PDP DW Centerstage Drumset",
            nameNormal:"PDP by DW Centerstage Standard Diamond Green Sparkle",
            name:"PDP by DW Centerstage\nStandard Diamond Green...",
            prize:"572",
            stars:STARS.stars2,
            altStars:"2 stars",
            id:"15",
        },
        {
            image:require('../assets/images/drumset4.jpg'),
            altImage:"Pearl Midtown Drumset",
            nameNormal:"Pearl Midtown Matte Red",
            name:"Pearl Midtown Matte Red\n\n",
            prize:"629",
            stars:STARS.stars3,
            altStars:"3 stars",
            id:"16",
        },
        {
            image:require('../assets/images/malletstation.jpg'),
            altImage:"Pearl Malletstation",
            nameNormal:"Pearl EM1 Malletstation",
            name:"Pearl EM1 Malletstation\n\n",
            prize:"1,825",
            stars:STARS.stars5,
            altStars:"5 stars",
            id:"17",
        },
        {
            image:require('../assets/images/djembe.jpg'),
            altImage:"Gewa Djembe Urban",
            nameNormal:"Gewa Djembé Urban Series 12\"",
            name:"Gewa Djembé Urban Series\n12\"",
            prize:"162",
            stars:STARS.stars3,
            altStars:"3 stars",
            id:"18",
        },
        {
            image:require('../assets/images/maracas.jpg'),
            altImage:"Sela Maracas",
            nameNormal:"Sela SEPMC1 Maracas",
            name:"Sela SEPMC1 Maracas\n\n",
            prize:"29.90",
            stars:STARS.stars3,
            altStars:"3 stars",
            id:"19",
        },
        {
            image:require('../assets/images/cowbell.jpg'),
            altImage:"NP Wood Block",
            nameNormal:"Meinl STB80BHH-S Cowbell",
            name:"Meinl STB80BHH-S\nCowbell",
            prize:"57",
            stars:STARS.stars4,
            altStars:"4 stars",
            id:"20",
        },
        {
            image:require('../assets/images/Gong.jpg'),
            altImage:"Paiste Gong Energy",
            nameNormal:"Paiste Gong 34\"Energy", 
            name:"Paiste Gong 34\"\nEnergy",     
            prize:"1,940",
            stars:STARS.stars4,
            altStars:"4 stars",
            id:"21",
        },
        {
            image:require('../assets/images/Cajon.jpg'),
            altImage:"Pepote Cajon Jaleo",
            nameNormal:"Pepote Cajon Jaleo Green",
            name:"Pepote Cajon Jaleo Green\n\n",   
            prize:"141",
            stars:STARS.stars5,
            altStars:"5 stars",
            id:"22",
        },
        {
            image:require('../assets/images/TubularBells.jpg'),
            altImage:"Adams Symphonic Campanologist",
            nameNormal:"Adams BK3216 Symphonic Campanologist",
            name:"Adams BK3216 Symphonic\nCampanologist",
            prize:"7,924",
            stars:STARS.stars4,
            altStars:"4 stars",
            id:"23",
        },
        {
            image:require('../assets/images/Surdo.jpg'),
            altImage:"Timbra Surdo Bahía",
            nameNormal:"Timbra Surdo 18\" Bahía Black",
            name:"Timbra Surdo 18\" Bahía\nBlack",
            prize:"232",
            stars:STARS.stars3,
            altStars:"3 stars",
            id:"24",
        },
        {
            image:require('../assets/images/BomboOrquesta.jpg'),
            altImage:"Bass Drum Band",
            nameNormal:"NP Bass Drum Band Standard 60x20 cm. Black",
            name:"NP Bass Drum Band\nStandard 60x20 cm. Black",
            prize:"379",
            stars:STARS.stars3,
            altStars:"3 stars",
            id:"25",
        }
    ];
    */